export const copy = {
  en: {
    play: 'Play',
    casual: 'Casual',
    ranked: 'Ranked',
    friend: 'Invite a friend',
    find: 'Find a player',
    home: 'Play',
    store: 'Store',
    cosmetics: 'Cosmetics',
    profile: 'Profile',
    history: 'History',
    leaders: 'Rankings',
    rules: 'Rules',
    settings: 'Settings',
    roll: 'Roll dice',
    confirm: 'Confirm turn',
    undo: 'Undo',
    surrender: 'Surrender',
    surrenderConfirm: 'Surrender this game? This counts as a loss.',
    waiting: 'Waiting for your opponent',
    cancel: 'Cancel',
    searching: 'Finding your opponent…',
    return: 'Return to game',
    share: 'Share invitation',
    open: 'Open in Telegram',
    tagline: 'A classic game. A new meeting place.',
    description: 'Long Nardy and Backgammon, together in Telegram.',
    beta: 'SEASON 0 · OPEN BETA',
    turn: 'Your turn',
    opponent: 'Opponent’s turn',
    reconnecting: 'Reconnecting…',
    connected: 'Connected',
    takeover: 'Continue on this device',
    controlLost: 'Game continued on another device',
    win: 'You won',
    loss: 'You lost',
    uncounted: 'Match not counted',
    again: 'Request rematch',
    accept: 'Accept',
    save: 'Save',
    nickname: 'Nickname',
    coins: 'Coins',
    level: 'Level',
    language: 'Language',
    sound: 'Sound',
    haptics: 'Haptics',
    mute: 'Mute opponent reactions',
    delete: 'Request account deletion',
    deleteConfirm: 'Disable your account now? You can restore it within 30 days.',
    more: 'Load more',
    restore: 'Restore account',
    long: 'Long Nardy',
    short: 'Backgammon',
    off: 'Bear off',
    bar: 'Bar',
    help: 'Tap a highlighted checker, then its destination. Undo freely; confirm the complete turn.',
    start: 'Start playing',
    tutorial: 'Quick tutorial',
    admin: 'Admin',
    error: 'Could not complete the action',
    close: 'Close',
    dailyReward: 'Daily Reward',
    dailyRewardAvailable: 'Daily Reward available',
    dailyRewardClaimed: "Today's reward claimed",
    dailyRewardUnavailable: 'Daily Reward unavailable',
    rewardCycle: '7-step reward cycle',
    day: 'Day',
    claim: 'Claim',
    claiming: 'Claiming…',
    claimed: 'Claimed',
    nextReward: 'Next reward in',
  },
  ru: {
    play: 'Играть',
    casual: 'Обычная',
    ranked: 'Рейтинговая',
    friend: 'Пригласить друга',
    find: 'Найти игрока',
    home: 'Играть',
    store: 'Магазин',
    cosmetics: 'Экипировка',
    profile: 'Профиль',
    history: 'История',
    leaders: 'Рейтинг',
    rules: 'Правила',
    settings: 'Настройки',
    roll: 'Бросить кости',
    confirm: 'Подтвердить ход',
    undo: 'Отменить',
    surrender: 'Сдаться',
    surrenderConfirm: 'Сдаться? Это будет засчитано как поражение.',
    waiting: 'Ожидаем соперника',
    cancel: 'Отмена',
    searching: 'Ищем соперника…',
    return: 'Вернуться в игру',
    share: 'Поделиться приглашением',
    open: 'Открыть в Telegram',
    tagline: 'Классическая игра. Новое место встречи.',
    description: 'Длинные и короткие нарды вместе в Telegram.',
    beta: 'СЕЗОН 0 · ОТКРЫТАЯ БЕТА',
    turn: 'Ваш ход',
    opponent: 'Ход соперника',
    reconnecting: 'Восстанавливаем связь…',
    connected: 'На связи',
    takeover: 'Продолжить на этом устройстве',
    controlLost: 'Игра продолжена на другом устройстве',
    win: 'Вы победили',
    loss: 'Вы проиграли',
    uncounted: 'Матч не засчитан',
    again: 'Реванш',
    accept: 'Принять',
    save: 'Сохранить',
    nickname: 'Никнейм',
    coins: 'Монеты',
    level: 'Уровень',
    language: 'Язык',
    sound: 'Звук',
    haptics: 'Вибрация',
    mute: 'Скрывать реакции соперника',
    delete: 'Удалить аккаунт',
    deleteConfirm: 'Отключить аккаунт? Восстановление доступно в течение 30 дней.',
    more: 'Загрузить ещё',
    restore: 'Восстановить аккаунт',
    long: 'Длинные нарды',
    short: 'Короткие нарды',
    off: 'Вывод',
    bar: 'Бар',
    help: 'Нажмите на выделенную шашку, затем на пункт назначения. Подтвердите полный ход.',
    start: 'Начать игру',
    tutorial: 'Краткое обучение',
    admin: 'Админ',
    error: 'Не удалось выполнить действие',
    close: 'Закрыть',
    dailyReward: 'Ежедневная награда',
    dailyRewardAvailable: 'Доступна ежедневная награда',
    dailyRewardClaimed: 'Награда за сегодня получена',
    dailyRewardUnavailable: 'Ежедневная награда недоступна',
    rewardCycle: 'Цикл из 7 наград',
    day: 'День',
    claim: 'Получить',
    claiming: 'Получаем…',
    claimed: 'Получено',
    nextReward: 'Следующая награда через',
  },
};
export type Language = keyof typeof copy;
export const rules = {
  en: {
    LONG_NARDY: [
      'Move all 15 checkers around the board into your home, then bear them off. Both players move in the same direction.',
      'A point occupied by any opponent checker is blocked. There are no hits or bar.',
      'Take only one checker from the head per turn. On the second player’s first turn, doubles 3–3, 4–4 and 6–6 permit two.',
      'You cannot make a six-point blockade trapping all 15 opposing checkers, even temporarily during your draft.',
      'Use the maximum possible number of dice. Doubles provide four moves. If only one of two different dice can be used, use the higher playable die.',
      'All remaining checkers must be in your last six points before bearing off. Oversized dice may remove only the farthest remaining checker.',
    ],
    BACKGAMMON: [
      'Move your 15 checkers toward your home, in the opposite direction to your opponent. Bear all of them off to win.',
      'Points with two or more enemy checkers are blocked. Landing on one enemy checker sends it to the bar.',
      'Checkers on the bar must re-enter before any other checker moves. If entry is blocked, that die cannot be used.',
      'The server rolls one opening die per player, repeats ties, and the higher roller uses both dice. Later rolls are manual.',
      'Use both dice whenever possible, or all four moves on doubles. If just one die can be played, the higher playable die is mandatory.',
      'Bear off only with all checkers home and none on the bar. Oversized dice remove the farthest remaining checker.',
      'NORMAL: opponent has borne off a checker. GAMMON: none borne off. BACKGAMMON: none borne off and a checker on the bar or in the winner’s home. All count as one result. No doubling cube.',
    ],
  },
  ru: {
    LONG_NARDY: [
      'Проведите все 15 шашек по доске в свой дом и выведите их. Оба игрока движутся в одном направлении.',
      'Пункт с любой шашкой соперника закрыт. Сбивания и бара нет.',
      'С головы снимается одна шашка за ход. На первом ходе второго игрока дубли 3–3, 4–4 и 6–6 разрешают снять две.',
      'Нельзя строить блок из шести пунктов, запирающий все 15 шашек соперника, даже временно в течение хода.',
      'Используйте максимально возможное число костей. Дубль даёт четыре движения. Если можно использовать лишь одну из разных костей — используется старшая из доступных.',
      'Выводить шашки можно, когда все оставшиеся шашки в последних шести пунктах. Избыточное значение позволяет вывести только самую дальнюю шашку.',
    ],
    BACKGAMMON: [
      'Проведите 15 шашек в свой дом и выведите их. Игроки движутся в противоположных направлениях.',
      'Две и более шашки соперника закрывают пункт. Одна шашка сбивается на бар.',
      'Все шашки с бара нужно ввести в дом соперника прежде, чем двигать остальные. Закрытый пункт не позволяет вход.',
      'Сервер бросает по одной кости каждому, повторяя равные броски. Старшая кость определяет первого игрока, который использует обе кости. Далее бросок ручной.',
      'Используйте обе кости, если возможно, или четыре движения при дубле. Если доступна только одна кость, обязательна старшая из доступных.',
      'Вывод возможен, когда все шашки дома и бар пуст. Избыточное значение выводит самую дальнюю оставшуюся шашку.',
      'NORMAL: соперник вывел шашку. GAMMON: не вывел ни одной. BACKGAMMON: не вывел ни одной и имеет шашку на баре или в доме победителя. Любой результат — одна победа. Куба удвоения нет.',
    ],
  },
};
export const avatarEmoji: Record<string, string> = {
  fox: '🦊',
  falcon: '🦅',
  otter: '🦦',
  lynx: '🐈',
};
export function message(language: Language, code: string): string {
  const values: Record<string, [string, string]> = {
    BEAR_OFF: ['All checkers borne off', 'Все шашки выведены'],
    SURRENDER: ['Surrender', 'Сдача'],
    TIMEOUT: ['Turn time expired', 'Время хода истекло'],
    ABANDON: ['Reconnect time expired', 'Время переподключения истекло'],
    START_TIMEOUT: ['Players did not join in time', 'Игроки не подключились вовремя'],
    NO_CONTEST: ['Match not counted — server error', 'Матч не засчитан — ошибка сервера'],
    INVALID_AUTH: ['Telegram authentication failed', 'Не удалось проверить вход через Telegram'],
    AUTH_EXPIRED: ['Reopen the Mini App to sign in', 'Откройте Mini App заново для входа'],
    ACCOUNT_DISABLED: ['Account is disabled', 'Аккаунт отключён'],
    UNAUTHENTICATED: ['Reopen the Mini App to sign in', 'Откройте Mini App заново для входа'],
    ACTIVE_MATCH_EXISTS: ['Return to your unfinished game', 'Вернитесь в незавершённую игру'],
    CHALLENGE_EXISTS: [
      'Cancel your current invitation first',
      'Сначала отмените текущее приглашение',
    ],
    CHALLENGE_UNAVAILABLE: [
      'Invitation has expired or was already used',
      'Приглашение истекло или уже использовано',
    ],
    SELF_ACCEPT: [
      'You cannot accept your own invitation',
      'Нельзя принять собственное приглашение',
    ],
    FORBIDDEN: [
      'This action is not available to your account',
      'Действие недоступно вашему аккаунту',
    ],
    CONTROL_LOST: ['Game continued on another device', 'Игра продолжена на другом устройстве'],
    STALE_VERSION: [
      'The board changed; please rebuild your turn',
      'Позиция изменилась — соберите ход заново',
    ],
    NOT_YOUR_TURN: ['Wait for your turn', 'Дождитесь своего хода'],
    TURN_NOT_STARTED: ['Wait for move presentation to finish', 'Дождитесь завершения показа хода'],
    ILLEGAL_TURN: ['Choose a complete legal turn', 'Выберите полный допустимый ход'],
    INVALID_COMMAND: [
      'The action was rejected; reconnect and try again',
      'Действие отклонено — переподключитесь и повторите',
    ],
    INVALID_NICKNAME: [
      'Choose a different nickname (3–24 letters or digits)',
      'Выберите другой никнейм (3–24 буквы или цифры)',
    ],
    NICKNAME_COOLDOWN: [
      'Nickname changes are available once every 7 days',
      'Никнейм можно менять раз в 7 дней',
    ],
    RATE_LIMIT: ['Too many actions; please wait', 'Слишком много действий — подождите'],
    NORMAL: ['Normal win', 'Обычная победа'],
    GAMMON: ['Gammon', 'Марс'],
    BACKGAMMON: ['Backgammon', 'Кокс'],
  };
  return (
    values[code]?.[language === 'ru' ? 1 : 0] ??
    (language === 'ru'
      ? 'Не удалось выполнить действие. Повторите попытку.'
      : 'The action could not be completed. Please try again.')
  );
}
